baseURL = 'https://fonzi.xyz'
languageCode = 'en-us'
title = 'Fonzi Vazquez'
theme = "hugo-theme-monochrome"
defaultContentLanguage = "en"
enableRobotsTXT = true
[params]
footer = '<p><a href="https://github.com/fonzi">Github</a> <a href="https://www.linkedin.com/in/vazquezalfonso/">LinkedIn</a> <a href="https://fonzi.xyz/index.xml">RSS</a> <a href="mailto:me@fonzi.xyz">E-Mail</a> </p>'
menu = 'main'
enable_site_search = true # default: false
enable_open_graph = true # default: true
enable_zooming_js = true # default: true
author = 'Fonzi Vazquez'
description = 'Tech rants and maybe some tutorials.'
title = "Fonzi's site"
images = ["skull.png"]
[[menu.navbar]]
identifier = "Blog"
name = "Blog"
title = "Blog"
url = "/blog/"
weight = 2
#[[menu.navbar]]
#identifier = "About"
#name = "About"
#title = "About"
#url = "/about/"
#weight = 3
#[[menu.navbar]]
#identifier = "Tutorials"
#name = "Tutorials"
#title = "Tutorials"
#url = "/tutorials/"
#weight = 4
[[menu.navbar]]
identifier = "Searx"
name = "Searx"
title = "Searx"
url = "https://searx.fonzi.xyz"
weight = 5

[[menu.navbar]]
identifier = "Tor"
name = "Tor"
title = "Tor"
url = "http://t7mhyj7a3ukowy6zpsmymxcrpspjxaqwlhmvfpf34cstzoj6c7lupxyd.onion"
weight = 10

[outputs]
home = ["HTML", "RSS", "JSON"]

[author]
name = "Fonzi Vazquez"
homepage = "https://fonzi.xyz"


[minify]
  disableCSS = false
  disableHTML = false
  disableJS = false
  disableJSON = false
  disableSVG = false
  disableXML = false
  minifyOutput = false
  [minify.tdewolff]
    [minify.tdewolff.css]
      keepCSS2 = true
      precision = 0
    [minify.tdewolff.html]
      keepComments = false
      keepConditionalComments = true
      keepDefaultAttrVals = true
      keepDocumentTags = true
      keepEndTags = true
      keepQuotes = false
      keepWhitespace = false
    [minify.tdewolff.js]
      keepVarNames = false
      noNullishOperator = false
      precision = 0
    [minify.tdewolff.json]
      keepNumbers = false
      precision = 0
    [minify.tdewolff.svg]
      keepComments = false
      precision = 0
    [minify.tdewolff.xml]
      keepWhitespace = false

